s=set()

number=int(input("enter numbers 1 : "))
s.add(int(number))
number=int(input("enter numbers 2 : "))
s.add(int(number))
number=int(input("enter numbers 3 : "))
s.add(int(number))
number=int(input("enter numbers 4 : "))
s.add(int(number))
number=int(input("enter numbers 5 : "))
s.add(int(number))
number=int(input("enter numbers 6 : "))
s.add(int(number))
number=int(input("enter numbers 7 : "))
s.add(int(number))
number=int(input("enter numbers 8 : "))
s.add(int(number))

print(s)
